package commands

import (
	"context"

	"github.com/spf13/cobra"

	"github.com/projectsveltos/sveltosctl/internal/actions/kubeconfig"

	"github.com/projectsveltos/sveltosctl/internal/logging"
	"github.com/projectsveltos/sveltosctl/internal/utils"

	ictx "github.com/projectsveltos/sveltosctl/internal/ctx"
)

type kubeconfigOptions struct {
	Namespace           string
	ServiceAccount      string
	Create              bool
	ExpirationSeconds   int
	ServiceAccountToken bool
}

const (
	projectSveltos   = "projectsveltos"
	kubeConfigCtxKey = ictx.ContextKey("cmdKubeConfigOptions")
)

func newKubeconfigOptions() *kubeconfigOptions {
	return &kubeconfigOptions{}
}

func addKubeconfigOptionsToContext(ctx context.Context, kubeConfigOptions *kubeconfigOptions) context.Context {
	ctx = context.WithValue(ctx, kubeConfigCtxKey, kubeConfigOptions)
	return ctx
}
func getKubeConfigOptions(ctx context.Context) *kubeconfigOptions {
	kco, ok := ctx.Value(kubeConfigCtxKey).(*kubeconfigOptions)
	if !ok || kco == nil {
		panic("no kubeconfigo pptions found in context")
	}
	return kco
}

func cmdKubeconfig(kubeConfigCmdOptions *kubeconfigOptions) *cobra.Command {
	kubeConfigCmd := &cobra.Command{
		Use: "kubeconfig",
		Short: `This command helps you set up credentials (kubeconfig) to access a Kubernetes cluster using Sveltos. It allows you to specify a ServiceAccount
or create a new one with the necessary permissions.`,
		Long: `Sveltos will either use an existing ServiceAccount with sufficient permissions (if --create is not set) or create a new one with
		cluster-admin permissions (if --create is set).
		Sveltos will generate a TokenRequest for the chosen ServiceAccount. Based on the TokenRequest, Sveltos will generate a kubeconfig
		file and output it.
		The Kubeconfig can then be used with "sveltosctl register cluster" command.`,
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()
			ctx = addKubeconfigOptionsToContext(ctx, kubeConfigCmdOptions)
			cmd.SetContext(ctx)
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()
			kco := getKubeConfigOptions(ctx)
			logger := logging.LoggerFromContext(ctx)
			err := kubeconfig.GenerateKubeconfigForServiceAccount(
				ctx,
				utils.GetAccessInstance().GetConfig(),
				kco.Namespace,
				kco.ServiceAccount,
				kco.ExpirationSeconds,
				kco.Create,
				true,
				kco.ServiceAccountToken,
				logger,
			)
			if err != nil {
				return err
			}
			return nil
		},
	}
	kubeConfigCmd.Flags().StringVarP(
		&kubeConfigCmdOptions.Namespace,
		"namespace",
		"n", projectSveltos,
		"Specifies the namespace of the ServiceAccount to use. Defaults to \"projectsveltos\"")
	kubeConfigCmd.Flags().StringVar(&kubeConfigCmdOptions.ServiceAccount,
		"serviceaccount", projectSveltos,
		"Specifies the name of the ServiceAccount to use. Defaults to \"projectsveltos\"")
	kubeConfigCmd.Flags().BoolVar(&kubeConfigCmdOptions.Create, "create", false,
		`If set, Sveltos will create the necessary resources if they don't already exist:
- The specified namespace (if not already present)
- The specified ServiceAccount (if not already present)
- A ClusterRole with cluster-admin permissions
- A ClusterRoleBinding granting the ServiceAccount cluster-admin permissions

Defaults to false.
`)
	kubeConfigCmd.Flags().IntVar(&kubeConfigCmdOptions.ExpirationSeconds, "expirationSeconds", 0,
		`This option allows you to specify the desired validity period
(in seconds) for the token requested when generating a kubeconfig.
Minimum value is 600 (10 minutes).
If you don't provide this option, the issuer (where the kubeconfig points)
will use its default expiration time for the token.
Once you register a cluster using the kubeconfig generated by this command,
you can manage automatic token renewal through the
SveltosCluster.Spec.TokenRequestRenewalOption setting within the registered
SveltosCluster resource. This provides more control over token expiration and
renewal behavior.

Defaults to 0.
`)
	kubeConfigCmd.Flags().BoolVar(&kubeConfigCmdOptions.ServiceAccountToken, "service-account-token", false,
		`Use a non-expiring ServiceAccount token for management cluster registration.
When enabled, Sveltos will automatically create the necessary ServiceAccount infrastructure
(ServiceAccount, ClusterRole, and ClusterRoleBinding) in the managed cluster and
generate a long-lived token by also creating a Secret of type kubernetes.io/service-account-token.

Defaults to false.
`)
	return kubeConfigCmd
}
